apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: istio-system
  name: kiali-secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["cacerts", "istio-ca-secret"]
  verbs: ["get"]