apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: istio-system
  name: kiali-secret-reader-binding
subjects:
- kind: ServiceAccount
  name: kiali-operator
  namespace: openshift-operators
roleRef:
  kind: Role
  name: kiali-secret-reader
  apiGroup: rbac.authorization.k8s.io