apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-customer
  template:
    metadata:
      labels:
        app: virtual-customer
        {{- if eq .Values.useMesh true }}
        sidecar.istio.io/inject: "true"
        {{- end }}
        version: "{{ .Chart.AppVersion }}"
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: virtual-customer
        image: {{ .Values.virtualCustomer.image.repository }}:{{ .Values.virtualCustomer.image.tag }}
        env:
        - name: ORDER_SERVICE_URL
          value: http://order-service:3000/
        - name: ORDERS_PER_HOUR
          value: "200"
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
          limits:
            cpu: 2m
            memory: 20Mi