apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-nothing
  namespace: pets
spec:
  {}
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-istio-gw-to-pets-ns
  namespace: pets
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/aks-istio-ingress/sa/aks-istio-ingressgateway-external"]
    - source:
        namespaces: ["aks-istio-ingress"]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-within-pets-ns
  namespace: pets
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["pets"]
