apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-shared-configmap-asm-1-23
  namespace: aks-istio-system
data:
  mesh: |-
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    defaultConfig:
      holdApplicationUntilProxyStarts: true
